# Generated by Django 2.0 on 2018-02-16 02:15

import clipboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('session_id', models.CharField(default=clipboard.models.get_default_id, max_length=8, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type_field', models.CharField(choices=[(0, 'Text'), (1, 'File')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('file', models.FileField(upload_to='documents/')),
                ('entry_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clipboard.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('text', models.CharField(max_length=1000)),
                ('entry_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clipboard.Entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clipboard.MediaType'),
        ),
    ]
