# Generated by Django 2.0 on 2018-02-13 03:08

import clipboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=clipboard.models.get_default_id, max_length=8)),
                ('data', models.CharField(max_length=1000)),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
