# Generated by Django 2.0 on 2017-12-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='session_id',
            field=models.CharField(default='WJBx4jsa', editable=False, max_length=8),
        ),
    ]
