# Generated by Django 2.0 on 2018-02-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0002_auto_20180221_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetaEntry',
            fields=[
                ('file_entry_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clipboard.TextEntry')),
                ('file_name', models.CharField(max_length=50)),
                ('file_length', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
            ],
        ),
    ]
