# Generated by Django 2.0 on 2017-12-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0002_auto_20171224_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='session_id',
        ),
    ]
