# Generated by Django 2.0 on 2017-12-24 22:49

import clipboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0003_remove_entry_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='session_id',
            field=models.CharField(default=clipboard.models.get_default_id, max_length=8),
        ),
    ]
