# Generated by Django 2.0 on 2018-04-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0004_auto_20180226_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.CharField(default='', max_length=10),
        ),
    ]
