# Generated by Django 2.0 on 2018-02-13 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0004_entry_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='creation_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
